# -*- coding: utf-8 -*-
"""Mod2_csII.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bfDZFALwZUUq8nWiDklq_LmSyAH5Vo1L
"""

#Write a program to find the factors of agiven  number and check whether the factor is even or odd
x=int(input("enter a number"))
i=2
c=[]
while(i!=x):
  if(x%i==0):
    c.append(i)
    #print(c)
  i=i+1
if(c==[]):
  print("factors of", x, "is 1 and", x)
else:
  print("Factors of ",x, "are ",c)
for n in c:
  if(n%2==0):
    print("factor",n ,"is even no")
  else:
     print("factor ",n, "is odd no")

#Write a code that accepts a sequence of words as input and prints the words in a sequence after sorting them alphabetically.
word=str(input("Enter a statement"))
c=word.split()
c.sort()
print(c)

#Write a program, whichwill find all the numbers between 1000 and 3000 (both included) such that each digit of a number is an even number. 
#The numbers obtained should be printed in a comma separated sequence on a single line

numbers = []
for x in range (1000, 3001):
    numSplit = [int(d) for d in str(x)]
    odd = False
    for y in range (0, len(numSplit)):
        if numSplit[y] % 2 != 0:
            odd = True
    if (odd == False):
        numbers.append(x)
print (numbers)

#4.Write a program that accepts a sentence and calculate the number of letters and digits.
word="Python0325"
letters=0
numbers=0
c=word.split()
for char in word:
  if(char.isdigit()):
    numbers=numbers+1
  else: 
    letters=letters+1
print("The number of letter is :",letters,"and numvers is", numbers)

#5
num=int(input("enter the number :"))
x=num
rev_no=0
while(num!=0):
  digit=num%10
  rev_no=rev_no*10+digit
  num=num//10
if(rev_no==x):
  print(rev_no,"Number is Pallindrome")
else:
  print(x,"is not a pallindrome")