# -*- coding: utf-8 -*-
"""Mod9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LWnEJyiyJlWArLKPc_94lmsJ95rUMCFZ
"""

import pandas as pd
import numpy as np
data={'float_col':[0.1,0.2,0.2,10.1,None],'int_col':[1,2,6,8,-1],'str_col':['a','b',None,'c','a']}
df=pd.DataFrame(data)
print(df)

x1=df.iloc[:,:2]
print(x1)

result=df[df['float_col']>0.15]
print(result)
print("-------------")
print(df[df['float_col']==0.1])

#Filter  the  records  fromtheDataFramewhich  satisfies  both  the  conditions float_colgreater than 0.1 and int_colgreater than 2
result=df[(df['float_col']>0.1)& (df['int_col']>2)]
print(result)

result=df[df['float_col']<=0.1]
print(result)

df1=df.rename(columns={'int_col':'INT_COl'},inplace=False)
print(df1)

df.rename(columns={'int_col':'INT_COl'},inplace=True)
print(df)

print(df.dropna())

x=df.loc[pd.isna(df["float_col"]), :].index
df['float_col'][x]=df['float_col'].mean()
print(df)
#print(df.loc[pd.isnull(df).any(1), :].index.values)

x=df.loc[pd.isna(df["str_col"]), :].index
df['str_col'][x]='e'
df['str_col'] = "map_" + df['str_col'].replace(np.nan,'no value').astype(str)
print(df)

df.groupby('str_col', as_index=False)['float_col'].mean()

df.cov()

df.corr()

data={'some_val ':[1,2],'str_col':['a','b']}
other=pd.DataFrame(data)
print(other)

print(pd.merge(df,other,on='str_col',how='inner'))

pd.merge(df,other,on='str_col',how='outer')

pd.merge(df,other,on='str_col',how='left')

pd.merge(df,other,on='str_col',how='right')

file_obj_4=open('names.txt','w')
file_obj_4.write("Anil\n")
file_obj_4.write("Sunita\n")
file_obj_4.write("Suman\n")
file_obj_4.write('Lokesh\n')
file_obj_4.write("Sumita\n")
file_obj_4.write("JohnJohny")

file_obj=open('body.txt','w')
file_obj.write("I am going to Delhi. Let’s meet on 7th Jan 2018\nHave a great day\n\nRegards\nTeam Victory")

file_obj_5=open('names.txt','r')
data_4=file_obj_5.read()
print(file_obj.tell())

with open("names.txt",'r',encoding = 'utf-8') as names_file:
  with open("body.txt",'r',encoding = 'utf-8') as body_file:
    body = body_file.read()
    for name in names_file:
      mail = "Hello "+name + body
      with open(name.strip()+".txt",'w',encoding = 'utf-8') as mail_file:
        mail_file.write(mail)